dist: xenial
language: node_js
node_js:
    - 14
services:
  - docker
env:
  - img=existdb/teipublisher:6.0.0-RC1
before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img
  - npm prune
install:
  - npm install -q
before_script:
  - docker start exist-ci
  # exist needs time
  - sleep 30
script:
    - npm test