dist: xenial
language: node_js
node_js:
    - 14
env:
  global:
    secure: m7ic+7t5poqDhoNr+UItJjxTzWVY7ah7r1fvea/RWzQdPOXpArtvPOtBFZ0vjRJv8b8WM5fazUSdnyW7X6kDvrLaphIkW6y77VqQnQBxVwOVQPI5rUqShLD0v34PXk/UogRh2L8n7hgaK7heACTe6FGDW4sy/WZlUlMD/U0nwZyqwlNK9Gr+gpExg2ckZ59pDB4mTUhrXO/ng8i2wVta4rQ/xcYxrJM0lJEaXbW9mF1HekytJcc0Fc0YTrbDNwUhQ+zBzCCCPnvDIgnpyjItC7lxj6p3Ml5jL3iEA2guxR+VsD/EpgnPhdcaXPIVjjKGdKQ4LYjaDRlmB0RVsgXj2xAN3T3+eUEofMBQaJ80FLWE6AdlmfFcm+s5x3Snnw8alO/KS/ZK+x9JHpXtUpsGjzIg0siPMx3yMBF2A9F/7RhtcJgZTzPAt/eVddvNXaMI6Dl+J3+Vsc0Xv3VgtFFyO6fVS2pvEFsOdiBATD3kRb8kw162NBD+rJ86EIHO/Oc1eO35me58Qearq7a3GZ7WmsAFwr1TrxaI170uMEv7RpJOLZWVKyuOCwD/7+Pp3UHya9UYScyij+uwiIZ2Bxu/+hUabgTiizS5S62+yyLId3pJHPwVdFs8AHP67qcKsgsWSRO7ra5hBmtZ661zrzF4wHW+BVQS6wAMqcT0riwHOKw=
script:
    - npm run test -- --endpoint $ENDPOINT --passwd $PASSWD
