name: tei-publisher-components CI

on:
  pull_request:
    branches: [ master, develop ]

  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install and build
        run:
          npm ci
          npm run build:production
      - name: Build docker image
        run: docker build -t exist-db -f Dockerfile .
      - name: Start docker image
        run: docker run --publish 8080:8080 --detach exist-db
      - name: Wait for eXist
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8080/exist/apps/tei-publisher/index.html
      - name: npm test
        run: npm test